platform: linux

image_resource:
  type: docker-image
  source:
    repository: azul/zulu-openjdk
    tag: "11"

inputs:
- name: source-code

caches:
  - path: .m2/

run:
  path: source-code/ci/tasks/package.sh
