jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package8
    privileged: true
    file: source-code/ci/tasks/package8.yml
  - task: package11
    privileged: true
    file: source-code/ci/tasks/package11.yml
